### ISSUE TITLE
JavaScript Exception: init failed:not supported argument 

### ISSUE THREAD

**Issue by BoneLiu** [kinosang/RsaSignatureDynamicValue#1]
I got a WARING as the issues title , when I use the Signature extensions in request->body->Form URL-encoded as the value of the key [Signature].  please help!
<img width="957" alt="warning" src="https://user-images.githubusercontent.com/12694684/81692652-4ced2480-9491-11ea-9b7c-c775f0f6d1c9.png">

**Comment by kinosang** [comment]
I'll check it asap.

**Comment by kinosang** [comment]
@BoneLiu sorry for the delay.

It seems you use a wrong private key, please add `-----BEGIN RSA PRIVATE KEY-----` and `-----END RSA PRIVATE KEY-----`.

I'll make a patch to support keys without the leading and trailing comments.
